### PR TITLE
Checkout hooks

### PR DESCRIPTION
**Pull request by jagger**
Adding example of checkout hook scripting

### CODE REVIEW

**Review by ConagherL — APPROVED** [review]
Reviewed

**Review by ConagherL — APPROVED** [review]

**Review by ConagherL — COMMENTED** [review]
Approved

**Review by ConagherL — APPROVED** [review]

**Comment by jagger** [comment]
Merging

**Comment by jagger** [comment]
Merging

**Comment by jagger** [comment]
Merge

**Review by ConagherL — APPROVED** [review]
This code is good

**Pull request merged**
